### ISSUE TITLE
Service point IDs not persistent, how to pass on the right service point when creating a new parcel over the API

### ISSUE THREAD

**Issue by iamniels** [SendCloud/spp-integration-example#1]
Currently we pass on the service point id in the "to_service_point" field. But the persistence is less than 15 minutes, so we run into errors.

Can we fix this by passing the whole object like below in the "to_service_point" field? Is this the intended use of this field?

    {
    "id": 10410599,
    "code": "167164",
    "is_active": true,
    "extra_data": {},
    "name": "Gamma",
    "street": "Hazenkamp",
    "house_number": "16",
    "postal_code": "6836BA",
    "city": "Arnhem",
    "latitude": "51.949303",
    "longitude": "5.883240",
    "email": "",
    "phone": "026-3270030",
    "homepage": "",
    "carrier": "postnl",
    "country": "NL",
    "formatted_opening_times": {
        "0": [
            "09:00 - 21:00"
        ],
        "1": [
            "09:00 - 21:00"
        ],
        "2": [
            "09:00 - 21:00"
        ],
        "3": [
            "09:00 - 21:00"
        ],
        "4": [
            "09:00 - 21:00"
        ],
        "5": [
            "09:00 - 18:00"
        ],
        "6": [
            "10:00 - 17:00"
        ]
    },
    "open_tomorrow": true,
    "distance": 0,
    "distanceStr": "0 m"
    }

**Comment by pedrospdc** [comment]
What do you mean by persistence is less than 15 minutes?

Service points are volatile and they're changed all the time by carriers, so we can't allow that. That's also the reason why we only allow people to check service points through this lib - they have to be selected at the time of ordering (preferably, or later).

If a label announcement failed due to a bad service point ID that was *recently* selected that's likely you were just really unlucky.

**Comment by pedrospdc** [comment]
What do you mean by persistence is less than 15 minutes?

Carriers often change service points but they they're not that volatile - generally carriers update their list of service points once a month, and they only change if new ones are added or removed. The IDs should remain for quite a while.

But unfortunately, we can't make the change you proposed. The reason why we only allow people to check service points through this lib  as service points selected at the time of ordering would always exist. If there's a delay between ordering and shipping and a label announcement failed due to a bad service point ID that was recently selected that's likely you were just really unlucky.

**Comment by iamniels** [comment]
Hi Pedro, thank you for your swift reply. 

I checked, and it was not 15 minutes. Here are several examples of failed calls:

- Customer ordered December the 17th at 22h, we called the API at the 19th 14h, service point Gamma
Hazenkamp 16, 6836BA, Arnhem
- Customer ordered December 17th at 22h, we called the API at the 19th 16h, service point GSM Plaza
Ginnekenweg 77 4818JB Breda
- Customer ordered December 18th 02h, we called the API at the 18th 10h, service point Primera, G.j. Van Heekstraat, Enschede

So it seems that a lot of PostNL service point ids changed on the 18th overnight.

**Comment by pedrospdc** [comment]
Hi @iamniels , thanks for the response. Would you have the ID's of the service points that went missing?

We received more complaints of API users about service points going missing. We're investigating the issue.

**Comment by pedrospdc** [comment]
If you also have some parcel ids that could be really helpful :-)

**Comment by iamniels** [comment]
Service point 10247825, shipment id 17562783

**Comment by erickwilder** [comment]
Given the age of this issue I'm closing it for now. Feel free to reopen if this is still relevant
