### ISSUE TITLE
Failure callback, reason: Invalid language set: en

### ISSUE THREAD

**Issue by marcdelange12345** [SendCloud/spp-integration-example#3]
Since a few days I receive the following error: 
Failure callback, reason: Invalid language set: en

All Languages are failing, also capitals does not make sense. 

I even receive it with the Demo Page: 
https://sendcloud.github.io/spp-integration-example/

Any suggestions?

**Comment by marcdelange12345** [comment]
Works if they adjust the language code: 
  'language': language, // string (e.g. en, fr, nl, de)
            // you can filter service points by carriers as well.

Should be nl-nl instead of nl

**Comment by erickwilder** [comment]
@marcdelange12345 
Indeed, all language codes must use the full language codes with their respective regions. This change was introduced to support cases like `en-us` and `en-gb` because some terms change between English locales (and we want to offer a better experience to the local market of shop owners)
