### ISSUE TITLE
What is the type of `to_service_point` ?

### ISSUE THREAD

**Issue by i-n-g-m-a-r** [SendCloud/spp-integration-example#7]
https://docs.sendcloud.sc/api/v2/shipping/
```
Get a specific parcel
--> Response values
  --> to_service_point
    ----> string <----

Create a parcel
--> Shipping service
  --> to_service_point
    ----> integer <----
```

**Comment by i-n-g-m-a-r** [comment]
wakker worden @erickwilder

**Comment by erickwilder** [comment]
@i-n-g-m-a-r this is indeed not ideal. We can patch it in our API responses, but then this will introduce a change of the current behaviour and any API consumer that already deals with this inconsistency may get unexpected results.

I'll discuss this with the team to check if we can fix this while maintaining backwards compatible

**Comment by i-n-g-m-a-r** [comment]
The main issue for me is not knowing what to expect.
On my end I will validate incoming data.
Converting a string/binary to an integer is not a problem unless the inbound value contains characters other than 0-9.
It looks like `to_service_point` should be an integer, but I can't be sure.

**Comment by erickwilder** [comment]
You're correct. It should be an integer and if we decide to change this baheviour that would be the only data type to be expected

**Comment by philipp-rudloff-sendcloud** [comment]
Without exception, service point IDs are indeed always integer-likes and can be safely cast to one should they be received in the form of a string.

I’m closing this because the incorrect API endpoint (i.e. Get a specific parcel via `/api/v2/parcels/{id}`) has existed like this for a quite a while now and changing it, while technically correct, would still be a breaking change. I will still file an internal ticket for addressing this and leave this to the respective team.
